name: Nightly Audit

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # see https://github.com/actions/virtual-environments for available environments
  SWIFT_VERSION: "5.6"

jobs:

  build_validator:
    name: Build validator
    runs-on: ubuntu-20.04
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Build validator
        run: |
          git clone https://github.com/SwiftPackageIndex/PackageList-Validator.git --depth 1
          cd PackageList-Validator
          swift build
          cp $(swift build --show-bin-path)/validator $GITHUB_WORKSPACE/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            validator

  check_redirects:
    name: Check redirects
    needs: build_validator
    runs-on: ubuntu-20.04
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Check redirect
        run: |
          chmod +x ./validator
          ./validator check-redirects -i packages.json -o redirect-checked.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            redirect-checked.json

  check_dependencies_0:
    name: Check dependencies 0
    needs: check_redirects
    runs-on: ubuntu-20.04
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Check dependencies
        run: |
          chmod +x ./validator
          ./validator check-dependencies -i redirect-checked.json -o out_0.json --chunk 0 --number-of-chunks 3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            out_0.json

  check_dependencies_1:
    name: Check dependencies 1
    needs: check_dependencies_0
    runs-on: ubuntu-20.04
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Check dependencies
        run: |
          chmod +x ./validator
          ./validator check-dependencies -i redirect-checked.json -o out_1.json --chunk 1 --number-of-chunks 3

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            out_1.json

  check_dependencies_last:
    name: Check dependencies 2
    needs: check_dependencies_1
    runs-on: ubuntu-20.04
    steps:
      - uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ env.SWIFT_VERSION }}

      # we need to check out the repo in the last step in order to create a PR
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Check dependencies
        run: |
          chmod +x ./validator
          ./validator check-dependencies -i redirect-checked.json -o out_2.json --chunk 2 --number-of-chunks 3
          ./validator merge-lists out_*.json -o packages.json
          # artifacts from appearing in the PR
          rm out_*.json redirect-checked.json validator

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Updated Packages
          title: '[Nightly] Updated Packages'
          body: |
            :robot: This is an automated change
            
            - Removed any redirects
            - Removed any duplicates
            - Removed any deleted repositories
            - Added any unknown dependencies

      - name: Check outputs
        run: echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
